name: detect_text_exam
data:
  file: data/detect_text_exam.tsv
  input:
    image: url
  output:
    result: bool
interface:
  prompt: Does the diagram contain text, letters or numbers?
training:
  setup:
    private_name: Training for detect text exam
    shuffle_tasks_in_task_suite: false
    assignment_max_duration_seconds: 600
    training_tasks_in_task_suite_count: 5
    retry_training_after_days: 1
    inherited_instructions: true
  data:
    file: data/detect_text_training.tsv
    input:
      image: url
    output:
      result: bool
project:
  setup:
    public_name: "[EXAM] Check if an image contains text, letters or numbers"
    public_description: Look at diagrams from science textbooks and state if they
      contain text, letters or numbers.
  instructions: instructions/detect_text_instructions.html
pool:
  estimated_time_per_suite: 10
  exam:
    history_size: 20
    min_answers: 20
    max_performers: 10
  setup:
    private_name: Exam for detecting text
    reward_per_assignment: 0.035
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 0
    golden_tasks_count: 5
    training_tasks_count: 0
  training:
    training_passing_skill_value: 70
  skill:
    id: 11432 # public skill on Toloka sandbox
quality_control:
  captcha:
    frequency: LOW
    success_rate: 80
    ban_duration: 3
    ban_units: DAYS
