name: verify_outlines_exam
data:
  file: data/verify_outlines_exam.tsv
  input:
    image: url
    outlines: json
  output:
    result: str
options:
  correct: "Yes"
  incorrect: "No"
  human_error: "Human error"
interface:
  prompt: Are all elements that contain text, letters or numbers outlined correctly?
training:
  setup:
    private_name: Training for verify outlines exam
    shuffle_tasks_in_task_suite: false
    assignment_max_duration_seconds: 300
    training_tasks_in_task_suite_count: 5
    retry_training_after_days: 1
    inherited_instructions: true
  data:
    file: data/verify_outlines_training.tsv
    input:
      image: url
      outlines: json
    output:
      result: str
project:
  setup:
    public_name: "[EXAM] Are all text, letters and numbers outlined correctly?"
    public_description: "Examine the diagram carefully and answer the following question: have all elements that 
                         contain text, letters or numbers been outlined according to the instructions?"
  instructions: instructions/verify_outlines_instructions.html
pool:
  estimated_time_per_suite: 15
  exam:
    history_size: 20
    min_answers: 20
    max_performers: 10
  setup:
    private_name: Exam for verifying outlines
    reward_per_assignment: 0.1
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 0
    golden_tasks_count: 5
    training_tasks_count: 0
  training:
    training_passing_skill_value: 70
  skill:
    id: 11433 # public skill on Toloka sandbox
quality_control:
  captcha:
    frequency: LOW
    success_rate: 80
    ban_duration: 3
    ban_units: DAYS
