name: detect_text
data:
  file: data/ai2d-rst_input_data.tsv
  input:
    image: url                    
  output:
    result: bool
actions:
  on_closed: aggregate_detect
interface:
  prompt: Does the diagram contain text, letters or numbers?
project:
  setup:
    public_name: Check if an image contains text, letters or numbers
    public_description: Look at diagrams from science textbooks and state if they
      contain text, letters or numbers.
  instructions: instructions/detect_text_instructions.html
pool:
  estimated_time_per_suite: 10
  setup:
    private_name: Detect text
    reward_per_assignment: 0.034
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 3
    default_overlap_for_new_task_suites: 3
  mixer:
    real_tasks_count: 5
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    skill:
      - 11432: 80 # public skill on Toloka sandbox
    client_type:
      - TOLOKA_APP
      - BROWSER
quality_control:
  fast_responses:
    history_size: 5
    count: 3
    threshold: 2
    ban_duration: 7
    ban_units: DAYS
  skipped_assignments:
    count: 3
    ban_duration: 7
    ban_units: DAYS
  captcha:
    frequency: LOW
    success_rate: 80
    ban_duration: 3
    ban_units: DAYS
