name: outline_text
data:
  input:
    image: url
  output:
    outlines: json
actions:
  on_submitted: verify_outlines
  on_rejected: outline_text
interface:
  prompt: Read the instructions first. Then outline all diagram elements that contain
          text, letters or numbers.
project:
  setup:
    public_name: Outline text, letters or numbers in diagrams
    public_description: Read the instructions first. Then outline all diagram elements that contain
                        text, letters or numbers.
  instructions: instructions/draw_outlines_instructions.html
training:
pool:
  estimated_time_per_suite: 30
  setup:
    private_name: Outline text
    reward_per_assignment: 0.1
    assignment_max_duration_seconds: 800
    auto_accept_solutions: false
    auto_accept_period_day: 3
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 1
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    skill:
      - 43736: 80
    languages:
      - EN
    client_type:
      - BROWSER
quality_control:
  captcha:
    frequency: LOW
    success_rate: 80
    ban_duration: 3
    ban_units: DAYS
