name: verify_outlines
data:
  input:
    image: url                          
    outlines: json
  output:
    result: str
options:
  correct: "Yes"
  incorrect: "No"
  human_error: "Human error"
actions:
  on_closed: aggregate_verify
interface:
  prompt: Read the instructions first. Is the diagram annotated according to the instructions?
project:
  setup:
    public_name: Verify outlines for text, letters or numbers in diagrams
    public_description: Look at diagrams from science textbooks and verify if they have
      been annotated correctly.
  instructions: instructions/verify_outlines_instructions.html
training:
pool:
  estimated_time_per_suite: 15
  setup:
    private_name: Verify outlines
    reward_per_assignment: 0.075
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 3
    default_overlap_for_new_task_suites: 3
  mixer:
    real_tasks_count: 1
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    skill:
      - 11433: 80 # public skill on Toloka sandbox
    languages:          
      - EN
    client_type:
      - BROWSER
      - TOLOKA_APP
quality_control:
  fast_responses:
    history_size: 5
    count: 3
    threshold: 2
    ban_duration: 7
    ban_units: DAYS
  captcha:
    frequency: LOW
    success_rate: 80
    ban_duration: 3
    ban_units: DAYS
