name: fix_outlines
data:
  input:
    image: url
    outlines: json
  output:
    outlines: json
actions:
  on_rejected: fix_outlines
  on_submitted: verify_outlines
interface:
  prompt: Read the instructions first. Then outline all diagram elements that contain
    text, letters or numbers.
project:
  setup:
    public_name: Add missing outlines for text, letters and numbers
    public_description: Look at diagrams from science textbooks and state if they
      contain text, letters or numbers.
  instructions: instructions/fix_outlines_instructions.html
pool:
  estimated_time_per_suite: 120
  setup:
    private_name: Fix outlines
    reward_per_assignment: 0.4
    assignment_max_duration_seconds: 800
    auto_accept_solutions: false
    auto_accept_period_day: 3
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 1
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    skill:
      - 11433: 80 # public skill on Toloka sandbox
    languages:
      - EN
    client_type:
      - BROWSER
quality_control:
  captcha:
    frequency: LOW
    success_rate: 80
    ban_duration: 3
    ban_units: DAYS
