name: outline_target
data:
  input:
    image: url
    outlines: json
  output:
    outlines: json
    no_target: bool
actions:
  on_submitted: verify_target_outlines
  on_rejected: outline_target
interface:
  prompt: Read the instructions first. Find the part of the diagram that the text refers to and draw accurate outlines for this part.
project:
  setup:
    public_name: "Outline elements in diagrams from school textbooks"
    public_description: "In this task you will be shown diagrams from school textbooks. Your task is to outline parts of the diagram."
  instructions: instructions/outline_targets_instructions.html
pool:
  estimated_time_per_suite: 90
  setup:
    private_name: Outline target
    reward_per_assignment: 0.3
    assignment_max_duration_seconds: 800
    auto_accept_solutions: false
    auto_accept_period_day: 3
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 1
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    skill:
      - 45441: 80
    languages:
      - EN
    client_type:
      - BROWSER
quality_control:
  captcha:
    frequency: LOW
    success_rate: 80
    ban_duration: 3
    ban_units: DAYS
