name: verify_target_outlines
data:
  input:
    no_target: bool
    image: url                          
    outlines: json
  output:
    result: bool
actions:
  on_closed: aggregate_verify_target
interface:
  prompt: Read the instructions first. Is the diagram annotated according to the instructions?
  labels:
    target: Target
    object: Source
  checkbox: The element marked as "Source" does not have a target.
project:
  setup:
    public_name: "Verify outlines for elements in diagrams from school textbooks"
    public_description: "In this task you will be shown outlined diagrams from school text books. Your task is to verify if the diagrams have been outlined correctly."
  instructions: instructions/verify_target_outlines_instructions.html
training:
pool:
  estimated_time_per_suite: 10
  setup:
    private_name: Verify outlines
    reward_per_assignment: 0.035
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 3
    default_overlap_for_new_task_suites: 3
  mixer:
    real_tasks_count: 1
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    skill:
      - 11434: 80 # public skill on Toloka sandbox
    languages:          
      - EN
    client_type:
      - BROWSER
      - TOLOKA_APP
quality_control:
  fast_responses:
    history_size: 5
    count: 3
    threshold: 2
    ban_duration: 7
    ban_units: DAYS
  captcha:
    frequency: LOW
    success_rate: 80
    ban_duration: 3
    ban_units: DAYS
